<?xml version="1.0" encoding="utf-8"?><Database Name="MKTing" Class="LinqtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HAN-L-3PFF7H2;Initial Catalog=MKTing;Integrated Security=True" SettingsObjectName="Maketting.Properties.Settings" SettingsPropertyName="MKTingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_MKT_DetailRpt_Phieuissue" Member="tbl_MKT_DetailRpt_Phieuissues">
    <Type Name="tbl_MKT_DetailRpt_Phieuissue">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="stt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soluong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bangchu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tensanpham" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Sophieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Temp" Member="tbl_Temps">
    <Type Name="tbl_Temp">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="System" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MakettingRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="storeright" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LoadRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WareHouseRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReportsRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Inventory" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InventoryAprroval" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StoreLocationmanage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="addNewProduct" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_headRpt_Phieuissue" Member="tbl_MKT_headRpt_Phieuissues">
    <Type Name="tbl_MKT_headRpt_Phieuissue">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nguoiyeucau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaythang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sophieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nguoinhancode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Nguoinhanname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="mucdich" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="dienthoai" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="seri" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Barcode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_khachhang" Member="tbl_MKT_khachhangs">
    <Type Name="tbl_MKT_khachhang">
      <Column Name="Customer_code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Customer_name" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="idCust" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_khoMKT" Member="tbl_MKT_khoMKTs">
    <Type Name="tbl_MKT_khoMKT">
      <Column Name="tenkho" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="makho" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="diachikho" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="storeright" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_ListLoadhead" Member="tbl_MKt_ListLoadheads">
    <Type Name="tbl_MKt_ListLoadhead">
      <Column Name="LoadNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date_Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Created_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingPoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransposterCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransposterName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Truckno" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_ListLoadheadDetail" Member="tbl_MKt_ListLoadheadDetails">
    <Type Name="tbl_MKt_ListLoadheadDetail">
      <Column Name="LoadNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingPoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Materiacode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Issued" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Serriload" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_Listphieu" Member="tbl_MKt_Listphieus">
    <Type Name="tbl_MKt_Listphieu">
      <Column Name="Gate_pass" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Date_Received_Issued" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Requested_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Customer_SAP_Code" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Receiver_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Purpose" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Item" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Materiacode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Issued" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ngaytaophieu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MateriaSAPcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Soluongdaxuat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Soluongconlai" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngayhoanthanh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Purposeid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingPoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Loadingby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipmentNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Shipmentby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tranposterby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Truck" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_Listphieuhead" Member="tbl_MKt_Listphieuheads">
    <Type Name="tbl_MKt_Listphieuhead">
      <Column Name="Gate_pass" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Date_Received_Issued" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Requested_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Customer_SAP_Code" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Receiver_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Purpose" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Ngaytaophieu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Purposeid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingPoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoadNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="completed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="completedby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tranposterby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Truck" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_LoaddetailRpt" Member="tbl_MKT_LoaddetailRpts">
    <Type Name="tbl_MKT_LoaddetailRpt">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="stt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soluong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bangchu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="materialcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="tensanpham" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_LoadHeadRpt" Member="tbl_MKT_LoadHeadRpts">
    <Type Name="tbl_MKT_LoadHeadRpt">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Loadnumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaythang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="shippingpoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Loadcreatebby" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="codetransporter" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="nametransporter" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Truckno" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="gatepasslist" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="seri" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Barcode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Mucdich" Member="tbl_MKT_Mucdiches">
    <Type Name="tbl_MKT_Mucdich">
      <Column Name="macT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenCT" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Nhacungungvantai" Member="tbl_MKT_Nhacungungvantais">
    <Type Name="tbl_MKT_Nhacungungvantai">
      <Column Name="tenNVT" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="maNVT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachiNVT" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="masothueNVT" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="dienthoaiNVT" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_POdetail" Member="tbl_MKt_POdetails">
    <Type Name="tbl_MKt_POdetail">
      <Column Name="POnumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaSAPcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaItemcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuantityOrder" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DatePO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BalanceQuantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Storelocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StatusPO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RecieptedQuantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IOcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IOname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Unit_Price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_POdetail_TMP" Member="tbl_MKt_POdetail_TMPs">
    <Type Name="tbl_MKt_POdetail_TMP">
      <Column Name="POnumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaSAPcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaItemcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuantityOrder" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Storelocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StatusPO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IOcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IOname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Unit_Price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_POhead" Member="tbl_MKt_POheads">
    <Type Name="tbl_MKt_POhead">
      <Column Name="PONumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Created_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DatePo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StoreLocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IOcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IOname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Stockcount" Member="tbl_MKT_Stockcounts">
    <Type Name="tbl_MKT_Stockcount">
      <Column Name="SAP_CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATERIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="END_STOCK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Store_code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CountingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Idsub" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Createdby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountQuantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Aproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Aprovedby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActualEndatAproval" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Stockend" Member="tbl_MKT_Stockends">
    <Type Name="tbl_MKT_Stockend">
      <Column Name="SAP_CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATERIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="END_STOCK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Store_code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_StoreRight" Member="tbl_MKT_StoreRights">
    <Type Name="tbl_MKT_StoreRight">
      <Column Name="makho" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="storeright" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_WHissueHeadRpt" Member="tbl_MKT_WHissueHeadRpts">
    <Type Name="tbl_MKT_WHissueHeadRpt">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Loadnumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaythang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Storeman" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Subid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="seri" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Barcode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="shippingpoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_WHstoreissue" Member="tbl_MKt_WHstoreissues">
    <Type Name="tbl_MKt_WHstoreissue">
      <Column Name="LoadNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingPoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Materiacode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IssueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Issued" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Serriload" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IssueBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IssueIDsub" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecieptQuantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Recieptby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="POnumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>