<?xml version="1.0" encoding="utf-8"?><Database Name="MKTing" Class="LinqtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HAN-L-3PFF7H2;Initial Catalog=MKTing;Integrated Security=True" SettingsObjectName="Maketting.Properties.Settings" SettingsPropertyName="MKTingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EinvoiceExport" Member="EinvoiceExports">
    <Type Name="EinvoiceExport">
      <Column Name="[Ngày hóa đơn]" Member="Ngày_hóa_đơn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Nhóm số hóa đơn]" Member="Nhóm_số_hóa_đơn" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Loại tiền tệ]" Member="Loại_tiền_tệ" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Ký hiệu]" Member="Ký_hiệu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Mã khách hàng]" Member="Mã_khách_hàng" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Họ tên người mua hàng]" Member="Họ_tên_người_mua_hàng" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Tên đơn vị]" Member="Tên_đơn_vị" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Mã số thuế]" Member="Mã_số_thuế" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Hình thức thanh toán]" Member="Hình_thức_thanh_toán" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Số Tài Khoản]" Member="Số_Tài_Khoản" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Tại ngân hàng]" Member="Tại_ngân_hàng" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Địa chỉ]" Member="Địa_chỉ" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Số điện thoại]" Member="Số_điện_thoại" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VAT10" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="VAT5" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Đvt" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Mã Hàng hóa]" Member="Mã_Hàng_hóa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Tên hành hóa, dịch vụ]" Member="Tên_hành_hóa__dịch_vụ" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Số lượng]" Member="Số_lượng" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Đơn giá]" Member="Đơn_giá" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Thành tiền]" Member="Thành_tiền" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Thuế suất GTGT]" Member="Thuế_suất_GTGT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Tiền Thuế GTGT]" Member="Tiền_Thuế_GTGT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Temp" Member="tbl_Temps">
    <Type Name="tbl_Temp">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="System" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MakettingRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="storeright" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LoadRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WareHouseRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReportsRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Inventory" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InventoryAprroval" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StoreLocationmanage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="addNewProduct" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IOprogamecreatRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Loadcreated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StoreIssue" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TransferOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TransferIN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChanelManage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IOmanageright" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SetPOSMprogrameright" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ViewProgramePDFright" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AprovalPaymentRequestright" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="updateGatePassDeliveredright" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RequestpaymentApproval" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="uploadBeginStoreright" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ControlUsername" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerEdit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerUploadright" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SalesLocationright" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SalesRegionManageright" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChannelsalesManageright" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReturnTicket" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="doMoreReturnticket" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="doViewcounting" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="changeProduct" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="deleteProduct" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_CustomerChanel" Member="tbl_MKT_CustomerChanels">
    <Type Name="tbl_MKT_CustomerChanel">
      <Column Name="Chanel_code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chanel_name" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_CustomerChaneltmp" Member="tbl_MKT_CustomerChaneltmps">
    <Type Name="tbl_MKT_CustomerChaneltmp">
      <Column Name="Chanel_code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chanel_name" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Select_channel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_DetailRpt_Phieuissue" Member="tbl_MKT_DetailRpt_Phieuissues">
    <Type Name="tbl_MKT_DetailRpt_Phieuissue">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="stt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soluong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bangchu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tensanpham" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Sophieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="thuhang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_headRpt_Phieuissue" Member="tbl_MKT_headRpt_Phieuissues">
    <Type Name="tbl_MKT_headRpt_Phieuissue">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nguoiyeucau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaythang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sophieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nguoinhancode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Nguoinhanname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="mucdich" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="dienthoai" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="seri" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Barcode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="thuhang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_IO_Programe" Member="tbl_MKT_IO_Programes">
    <Type Name="tbl_MKT_IO_Programe">
      <Column Name="IO_number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IO_Name" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Sales_Org" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChannelGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Avaiable_Budget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Spent_Budget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProgrameIDDocno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_IO_ProgrameTMP" Member="tbl_MKT_IO_ProgrameTMPs">
    <Type Name="tbl_MKT_IO_ProgrameTMP">
      <Column Name="ProgrameIDDocno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IO_number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IO_Name" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Sales_Org" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChannelGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_khoMKT" Member="tbl_MKT_khoMKTs">
    <Type Name="tbl_MKT_khoMKT">
      <Column Name="tenkho" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="makho" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="diachikho" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="storeright" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_ListLoadhead" Member="tbl_MKt_ListLoadheads">
    <Type Name="tbl_MKt_ListLoadhead">
      <Column Name="LoadNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date_Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Created_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingPoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransposterCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransposterName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Truckno" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="pallet" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_ListLoadheadDetail" Member="tbl_MKt_ListLoadheadDetails">
    <Type Name="tbl_MKt_ListLoadheadDetail">
      <Column Name="LoadNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingPoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Materiacode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Issued" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Serriload" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_Listphieudetail" Member="tbl_MKt_Listphieudetails">
    <Type Name="tbl_MKt_Listphieudetail">
      <Column Name="Gate_pass" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Date_Received_Issued" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Requested_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Customer_SAP_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Receiver_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Purpose" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Item" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Materiacode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Issued" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ngaytaophieu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MateriaSAPcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Soluongdaxuat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Soluongconlai" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngayhoanthanh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Purposeid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingPoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Loadingby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipmentNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Shipmentby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tranposterby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Truck" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Completed_by" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NetValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Returnby" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Returndate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReturnQuantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Delivery_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Issued_dated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Included_Shipment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pallet" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="shiptocity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Return_reason" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Returnrequest" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_Listphieuhead" Member="tbl_MKt_Listphieuheads">
    <Type Name="tbl_MKt_Listphieuhead">
      <Column Name="Gate_pass" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Date_Received_Issued" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Requested_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Customer_SAP_Code" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Receiver_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Purpose" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Ngaytaophieu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Purposeid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingPoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoadNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="completed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="completedby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tranposterby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShiptoCode" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ShiptoName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ShiptoAddress" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Trucknumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="requestReturn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DoiD" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="einvoice" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_LoaddetailRpt" Member="tbl_MKT_LoaddetailRpts">
    <Type Name="tbl_MKT_LoaddetailRpt">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="stt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soluong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bangchu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="materialcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="tensanpham" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_LoadHeadRpt" Member="tbl_MKT_LoadHeadRpts">
    <Type Name="tbl_MKT_LoadHeadRpt">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Loadnumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaythang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="shippingpoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Loadcreatebby" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="codetransporter" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="nametransporter" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="gatepasslist" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="seri" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Barcode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="pallet" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Nhacungungvantai" Member="tbl_MKT_Nhacungungvantais">
    <Type Name="tbl_MKT_Nhacungungvantai">
      <Column Name="tenNVT" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="maNVT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachiNVT" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="masothueNVT" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="dienthoaiNVT" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Palletrate" Member="tbl_MKT_Palletrates">
    <Type Name="tbl_MKT_Palletrate">
      <Column Name="[ITEM ]" Member="ITEM_" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="onPallet" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Payment_Aproval" Member="tbl_MKT_Payment_Aprovals">
    <Type Name="tbl_MKT_Payment_Aproval">
      <Column Name="IO_number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProgrameIDDocno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Customercode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="CustomerAddress" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="AprovalBudget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="costcenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="payID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Approval" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Requestby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Approvalby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Requsestdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Approvaldate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Payment_Aproval_head" Member="tbl_MKT_Payment_Aproval_heads">
    <Type Name="tbl_MKT_Payment_Aproval_head">
      <Column Name="Requestby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IO_number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TotalAprovalBudget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="costcenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="payID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Approval" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProgrameIDDocno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProgrameName" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Payment_AprovalTMP" Member="tbl_MKT_Payment_AprovalTMPs">
    <Type Name="tbl_MKT_Payment_AprovalTMP">
      <Column Name="IO_number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProgrameIDDocno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Customercode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="CustomerAddress" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="AprovalBudget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="costcenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_POdetail" Member="tbl_MKt_POdetails">
    <Type Name="tbl_MKt_POdetail">
      <Column Name="POnumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaSAPcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaItemcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuantityOrder" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DatePO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BalanceQuantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Storelocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StatusPO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RecieptedQuantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Unit_Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="inputRate" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_POdetail_TMP" Member="tbl_MKt_POdetail_TMPs">
    <Type Name="tbl_MKt_POdetail_TMP">
      <Column Name="POnumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaSAPcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaItemcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuantityOrder" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Storelocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StatusPO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IOcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IOname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Unit_Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="inputRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="POdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_POhead" Member="tbl_MKt_POheads">
    <Type Name="tbl_MKt_POhead">
      <Column Name="PONumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Created_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DatePo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StoreLocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IOcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IOname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Programe" Member="tbl_MKT_Programes">
    <Type Name="tbl_MKT_Programe">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProgrameIDDocno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenCT" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Fromdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Todate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="TotalBudget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UsedBudget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BalanceBudget" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Programepdfdata" Member="tbl_MKT_Programepdfdatas">
    <Type Name="tbl_MKT_Programepdfdata">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Contentype" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ProgrameIDDocno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Programepriceproduct" Member="tbl_MKT_Programepriceproducts">
    <Type Name="tbl_MKT_Programepriceproduct">
      <Column Name="ProgrameIDDocno" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SAP_CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATERIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_ProgramepriceproductTMP" Member="tbl_MKT_ProgramepriceproductTMPs">
    <Type Name="tbl_MKT_ProgramepriceproductTMP">
      <Column Name="SAP_CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATERIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProgrameIDDocno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Region" Member="tbl_MKT_Regions">
    <Type Name="tbl_MKT_Region">
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_SaleOrg" Member="tbl_MKT_SaleOrgs">
    <Type Name="tbl_MKT_SaleOrg">
      <Column Name="SaleOrg" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Soldtocode" Member="tbl_MKT_Soldtocodes">
    <Type Name="tbl_MKT_Soldtocode">
      <Column Name="Customer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShiptoCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Soldtype" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FullNameN" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Telephone1" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalesOrg" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentTerms" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PriceList" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyAcc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalesDistrict" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VATregistrationNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Createdon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Createby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chanel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Stockcount" Member="tbl_MKT_Stockcounts">
    <Type Name="tbl_MKT_Stockcount">
      <Column Name="SAP_CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATERIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="END_STOCK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Store_code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CountingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Idsub" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Createdby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountQuantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Aproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Aprovedby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActualEndatAproval" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Stockend" Member="tbl_MKT_Stockends">
    <Type Name="tbl_MKT_Stockend">
      <Column Name="SAP_CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATERIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="END_STOCK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Store_code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TransferingOUT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ordered" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RegionBudgeted" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ON_Hold" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Quantity_Per_Pallet" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="End_Stock_By_Pallet" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Stockenddailysave" Member="tbl_MKT_Stockenddailysaves">
    <Type Name="tbl_MKT_Stockenddailysave">
      <Column Name="SAP_CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATERIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="END_STOCK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Store_code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TransferingOUT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ON_Hold" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="End_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Stockendlocation" Member="tbl_MKT_Stockendlocations">
    <Type Name="tbl_MKT_Stockendlocation">
      <Column Name="location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SAP_CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATERIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="END_STOCK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Store_code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Stockendlocationdetail" Member="tbl_MKT_Stockendlocationdetails">
    <Type Name="tbl_MKT_Stockendlocationdetail">
      <Column Name="location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SAP_CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATERIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="END_STOCK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Store_code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Doctype" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DocNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_StockendRegionBudget" Member="tbl_MKT_StockendRegionBudgets">
    <Type Name="tbl_MKT_StockendRegionBudget">
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SAP_CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATERIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="QuantityInputbyPO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QuantityOutput" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuantityInputbyReturn" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QuantitybyDevice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Regionchangedate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Store_code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Gate_pass" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="POnumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="idsub" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityInputbytransferin" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DocumentNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DnNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="QuantityReceipt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Createdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_StockendTMP" Member="tbl_MKT_StockendTMPs">
    <Type Name="tbl_MKT_StockendTMP">
      <Column Name="SAP_CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATERIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="END_STOCK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Store_code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_Storelocation" Member="tbl_MKT_Storelocations">
    <Type Name="tbl_MKT_Storelocation">
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_StoreRight" Member="tbl_MKT_StoreRights">
    <Type Name="tbl_MKT_StoreRight">
      <Column Name="makho" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="storeright" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_TransferINdetail" Member="tbl_MKt_TransferINdetails">
    <Type Name="tbl_MKt_TransferINdetail">
      <Column Name="Tranfernumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaSAPcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaItemcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Transfer_OUT_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Transfer_IN_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Store_OUT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Store_IN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Reciepted_Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IssueIDsub" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_Transferindetailrpt" Member="tbl_MKt_Transferindetailrpts">
    <Type Name="tbl_MKt_Transferindetailrpt">
      <Column Name="stt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soluong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tensanpham" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bangchu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="masanpham" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="donvi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_TransferinoutHEADrpt" Member="tbl_MKt_TransferinoutHEADrpts">
    <Type Name="tbl_MKt_TransferinoutHEADrpt">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tranfernumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Created_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Transfer_OUT_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Transfer_IN_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Store_OUT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Store_IN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Trucknumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Seri" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Barcode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Subid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_Transferoutdetail" Member="tbl_MKt_Transferoutdetails">
    <Type Name="tbl_MKt_Transferoutdetail">
      <Column Name="Tranfernumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaSAPcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaItemcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Transfer_OUT_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Transfer_IN_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Store_OUT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Store_IN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AvaiableQuantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Reciepted_Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_Transferoutdetailrpt" Member="tbl_MKt_Transferoutdetailrpts">
    <Type Name="tbl_MKt_Transferoutdetailrpt">
      <Column Name="stt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soluong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tensanpham" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bangchu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="masanpham" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="donvi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_TransferoutdetailTMP" Member="tbl_MKt_TransferoutdetailTMPs">
    <Type Name="tbl_MKt_TransferoutdetailTMP">
      <Column Name="Tranfernumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaSAPcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaItemcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Transfer_OUT_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Transfer_IN_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Store_OUT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Store_IN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AvaiableQuantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QuantityInConfirm" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_TransferoutHEAD" Member="tbl_MKt_TransferoutHEADs">
    <Type Name="tbl_MKt_TransferoutHEAD">
      <Column Name="Tranfernumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Created_by" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Transfer_OUT_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Transfer_IN_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Store_OUT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Store_IN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Trucknumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKT_WHissueHeadRpt" Member="tbl_MKT_WHissueHeadRpts">
    <Type Name="tbl_MKT_WHissueHeadRpt">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Loadnumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaythang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Storeman" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Subid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="seri" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Barcode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="shippingpoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MKt_WHstoreissue" Member="tbl_MKt_WHstoreissues">
    <Type Name="tbl_MKt_WHstoreissue">
      <Column Name="LoadNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingPoint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Materiacode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Materialname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IssueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Issued" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Serriload" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IssueBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IssueIDsub" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecieptQuantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Recieptby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="POnumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MateriaItemcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="date_input_output" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DNNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Document_number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Transfer_number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Doc_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>